### PR TITLE
borsy bors bors

### PR DESCRIPTION
**Pull request by vitiral**
@killercup r?

This is just a test

### CODE REVIEW

**Comment by vitiral** [comment]
bors ping

**Comment by vitiral** [comment]
bors delegate= @killercup

**Comment by vitiral** [comment]
@killercup please approve, I'd just like to see the whole thing work correctly (I can delete the comment later).

**Comment by vitiral** [comment]
@killercup if you could also make sure the travis + appveyor files look good that would be great!

**Comment by vitiral** [comment]
bors try

**Comment by vitiral** [comment]
bors try

**Comment by vitiral** [comment]
bors r= @killercup

**Comment by vitiral** [comment]
Oh I see, you need `r=someone` to get the review process starting.

**Comment by killercup** [comment]
bors & travis LGTM, but I don't have any experience with appveyor.

Since you already r+'d bors seems to be doing its thing. Good job, bors! :)

**Pull request merged**
